### ISSUE TITLE
Problem with handling of low buffer levels

### ISSUE THREAD

**Issue by shashankkrjain** [dazedsheep/DASH-JS#1]
I am not sure if you are still developing this, but I would to bring to your notice a problem with the way current implementation handles buffer low levels.

In current implementation, when buffer level falls below critical level, the video playback stops until buffer is above critical level again. In effect, this results in actual buffer being equal to maxBuffer - criticalLevel.

I suggest you to make changes in it so that it handled in following way:
1. If buffer falls below critical level, refill is signaled. But, video chunks available in buffer are allowed to be played until buffer completely runs out.
2. If buffer doesn't run out completely and goes above critical level again, we saved a plackback stop!
3. If buffer does empty out, playback is stopped, and buffer is now allowed to refill until it is above critical level again. After that, video playback is resumed.

**Comment by dazedsheep** [comment]
Actually it should not stop the playback because refilling the buffer is signalled asynchronously (including the fetching of segments). I will test it and update it.

**Comment by shashankkrjain** [comment]
Actually, I did fix it, by modifying _drain_ function of _basebuffer_ like this:

```
if(dimension == "seconds")
    {

        if(this.fillState.seconds == 0 && this.streamEnded) return -1;

        if(this.fillState.seconds <= this.criticalState.seconds && !this.streamEnded) 
        {
            //> The fill state is going below critical level. Signal minimumLevel event
            this.callEvent("minimumLevel");

            //> But, if there is data in buffer, return that data if buffer underrun did not occur
            //> If there was buffer underrrun, we need to buffer for minimun buffer level before playing
            //> again
            if (this.fillState.seconds > 0 && this.underRunOccured == false) {

                this.fillState.seconds -= amount;
                return this.get();
            }
            else if (this.underRunOccured == false){
                //> Signal Buffer underrun
                console.log("Buffer underrun!");
                this.underRunOccured = true;
            }
        }
        else{
            //> Set under run occured false as there is enough buffer filled now
            this.underRunOccured = false;
            this.fillState.seconds -= amount;
            return this.get();
        }
    }       
```

Just create a boolean varibale _underRunOccured_ in basebuffer's definition.

**Comment by dazedsheep** [comment]
If you would be so kind and create a patch for this issue? - I will apply it.

**Comment by dazedsheep** [comment]
Thanks, fix applied and pull req. merged.
